### PR TITLE
[fixes] Multiple fixes, travis-ci and dependencies updates

### PR DESCRIPTION
**Pull request by dario1985**
With json !== false (undefined too) option throw a Uncaught TypeError: Cannot read property 'once' of undefined
Currently affects versions >=1.0.x

### CODE REVIEW

**Comment by dario1985** [comment]
I fixed old tests and added new enviroments (iojs3, node>=4.0 and mongodb-3.2-unstable) to "allow_failure" travis' matrix option set: there are still some issues compiling nan library with some enviroments.

Using nodejs-redis 2.x is not possible to pass the original option object, because the redis.createClient on connect do a clone (using JSON.stringify) and may contain complex objects (redis module, and sub connections) with circular references.

@mcollina do you think is ready to be merged?

**Comment by behrad** [comment]
+1 @dario1985 
Needed this to be able to build ascoltatori on node 4.2.x becauseI think we should really update node_redis to 2.3.x @mcollina 

Can you review and merge this in?

**Comment by dario1985** [comment]
@behrad this PR doesn't fix the build issues with node 4.x, just add it in the CI build matrix with "allow_failure" option on.

**Comment by behrad** [comment]
my issue was not CI, `npm install` fails after cloning repo on 4.2.2 on some modules like zmq, qlobber-fsq, ... and problems sounds to be on V8 and nan versions :)

**Comment by mcollina** [comment]
I'm really against in setting  `allow_failure` to true.

As @behrad said, we need full support for 4.2.2. If qlobber-fsq or zmq cannot be ported, then we should just drop them.

@davedoesdev how about releasing a version of qlobber-fsq that supports 4.2.2?

**Comment by behrad** [comment]
One issue with ascoltatori @mcollina is that, there exist a bunch of unrelated dependencies making repo heavy in dev setup and testing... Consider one who needs Redis backend and doesn't want AMQP, ...
It is a good consideration for Aedes or newer versions of ascoltatori to refactor to a adapter, multi module based architecture, so one only installs adapter they need along side it's own tests and environemt :)

**Comment by mcollina** [comment]
@behrad that is already in place for Aedes, see https://www.npmjs.com/search?q=mqemitter.

Maintaining this one is really a big burden.

**Comment by behrad** [comment]
Nice @mcollina , So I think asoltatori and mosca is not based on mqemitter however Aedes would be !?

**Comment by mcollina** [comment]
Yes. Mosca will move away from Ascoltatori the moment it integrates aedes.

**Comment by dario1985** [comment]
@mcollina `allow_failure` is just to track future compatibilty issues like on mongodb-testing versions, that can fail for third-party reasons without broke build.

In the meanwhile mosca and others projects use ascoltatori and it should permit to use latest deps. What do you propose?

**Comment by mcollina** [comment]
I prefer a broken build and knowing that something is broken.

We still need to fix node 4 & 5 compat.

**Comment by dario1985** [comment]
@mcollina I think we are losing the focus of this pull request: fix travis-ci build and **blocking** earlies dependencies's compatibility issues (redis, mongodb, ...), and not currently fix node 4 and 5 compatibility.

By the way, I can remove the `allow_failure` and don't track node 4 and 5 compat (like before) but I still think that it's not a good option to hide them.

**Comment by psorowka** [comment]
@mcollina while fixing ascoltatori seems to be a bigger issue, what would you think about setting up an upstream branch we can collectively work on for pushing that forward?

**Comment by davedoesdev** [comment]
Bit late to the party here, apologies. Do I need to do anything?

**Comment by davedoesdev** [comment]
Am working on Node 4 for qlobber-fsq if that helps any.

**Comment by psorowka** [comment]
Hi guys, I just keep posting on the node4 issues in this conversation.

I have forked the last commit from @dario1985 and am really close to a successful build.

- I have filed a (small) PR on qlobber-fsq (https://github.com/davedoesdev/qlobber-fsq/pull/3) which fixes the build issues on qlobber. When the maintainer of fs-ext merges in (https://github.com/baudehlo/node-fs-ext/pull/55) we even get rid of some deprecation errors from nan

- with zmq, version 2.14.0 successfully builds on node 4. The only issue I currently have, is that the current mosca version which is installed in devDependencies installs zmq@2.12.0 and the old ascoltatori version which is included from mosca even only install zmq@2.11.0 

so for now: wait for qlobber-fsq to be merged in and meanwhile we could fix the zmq dependencies in the master versions of ascoltatori and mosca to 2.14.0. Then we will at least have a successful build, let's hope that tests are passing then as well

**Comment by psorowka** [comment]
lol @davedoesdev I did actually not realize that you are the qlobber guy... :-D

**Comment by davedoesdev** [comment]
@psorowka np - sorry we were working on it at the same time!
I managed to get .travis.yml into something that Travis deems acceptable so the tests are running now. I'll check the results in the morning.

**Comment by psorowka** [comment]
grr I am really getting dizzy on this. 

- mosca is a devDependency of ascoltatori
- but mosca doesn't run on node4 yet, because ascoltatori doesn't run on node4
- the necessary changes don't seem to be minor, as mosca still depends on ascoltatori@0.21.1 .....

I fear we should update mosca to ascoltatori@1.1.0 first, before anything else is possible. Is their any reason against this @mcollina ?

**Comment by mcollina** [comment]
Whatever it takes :/
Il giorno sab 16 gen 2016 alle 01:26 Peter Sorowka <notifications@github.com>
ha scritto:

**Comment by davedoesdev** [comment]
qlobber-fsq 0.4.0 is now published, works on Node 4.2.4.

**Comment by behrad** [comment]
:+1:

**Comment by behrad** [comment]
What about zmq @mcollina ? Will you drop that?

**Comment by psorowka** [comment]
I will release PRs for both ascoltatori and mosca including zmq 2.14.0 later today. Then we should be good to go 

Gesendet mit TypeApp

**Comment by mcollina** [comment]
That's Perfect, thanks Peter!
Il giorno sab 16 gen 2016 alle 12:48 Peter Sorowka <notifications@github.com>
ha scritto:

**Comment by psorowka** [comment]
@davedoesdev have you tested your qlobber-fsq release with ascoltatori? I receive test failures with it on node 0.10

```
1) ascoltatori.FileSystemAscoltatore "before each" hook:
     Uncaught TypeError: Object ��xu+���<� ��k��(�mܳ2�I�P��҉ has no method 'equals'
      at async.eachLimit.initialized (node_modules/qlobber-fsq/lib/qlobber-fsq.js:928:46)
      at node_modules/async/lib/async.js:181:20
      at replenish (node_modules/async/lib/async.js:319:21)
      at node_modules/async/lib/async.js:330:15
      at Object.async.forEachLimit.async.eachLimit (node_modules/async/lib/async.js:220:35)
      at node_modules/qlobber-fsq/lib/qlobber-fsq.js:918:19
      at fs.js:272:14
      at node_modules/qlobber-fsq/node_modules/graceful-fs/graceful-fs.js:42:10
      at node_modules/mosca/node_modules/st/node_modules/graceful-fs/graceful-fs.js:42:10
      at Object.oncomplete (fs.js:108:15)

  2) ascoltatori.FileSystemAscoltatore "after each" hook for "should have a subscribe function":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by davedoesdev** [comment]
I removed `buffertools` in favour of the built-in `Buffer.equals` method.
TBH I don't really want to support anything earlier than LTS - Node don't seem to care much about backwards compatibility so why should modules?

**Comment by psorowka** [comment]
Okay that's what I expected. This implies stopping full support for node < 4 for ascoltatori and thus mosca as well. For me personally that's fine but might cause headaches for other people. @mcollina I think it's on you to have a thought on that. Other way would to use something like engine dependencies at least for the next few releases.

**Comment by mcollina** [comment]
I would prefer not to scrap that compatibility. How about using
https://github.com/substack/node-buffer-equal? It would possibly be super
slow on node < 4, but at least it would work.
Il giorno sab 16 gen 2016 alle 20:41 Peter Sorowka <notifications@github.com>
ha scritto:

**Comment by psorowka** [comment]
I would also suggest that we all start using the engines option, so we can see such (known and intended) incompatibilities while installing and not only after performing that one specific test to reveal it.

**Comment by psorowka** [comment]
But @mcollina that packet you propose seems to be a bad workaround. 

If @davedoesdev sticks to his mind, that would only mean that people that don't run at least iojs 3 or node 4 *and* need qlobber-fsq would either need to upgrade their node version (which is of advantage for performance but might be impossible when other dependencies aren't up to date)  or stick to the old ascoltatori version.

Is ascoltatori actually used anywhere else except mosca?

**Comment by davedoesdev** [comment]
`buffertools` does work on Node 4 but I've always been a little uncomfortable with native modules which are doing basic `Buffer` operations, so was pleased to be able to drop it in favour of `Buffer.equals`.
Putting support in would mean adding a Node version check into the code, which is rather sad.
Am happy to add an `engines` field.

**Comment by davedoesdev** [comment]
Btw: `Buffer.equals` was introduced in 0.12. So can we just drop 0.10 support?

**Comment by psorowka** [comment]
Ah cool I didn't quickly find I resource clearing when it was introduced. In my opinion that's a totally different story, node 0.12 should be quite well adopted

**Comment by davedoesdev** [comment]
OK I'll let you know when I get the tests to pass on 0.12 on Travis.

**Comment by mcollina** [comment]
Let's drop 0.10 and keep supporting 0.12. That should be the best course of
action.
Il giorno sab 16 gen 2016 alle 21:24 Peter Sorowka <notifications@github.com>
ha scritto:

**Comment by davedoesdev** [comment]
qlobber-fsq 0.4.1 is published with:

```json
  "engines": {
    "node": ">=0.12"
  }
```

Tests pass on 0.12 and 4.2.4

**Comment by psorowka** [comment]
I close this, as all changes from @dario1985 are merged in already. Thanks @dario1985!

**Pull request closed without merging**
