### PR TITLE
Added Google PubSub as a lib

### PR DESCRIPTION
**Pull request by bobvanluijt**
Hi all,

Love using Ascoltatori and Mosca but also wanted to use Google's PubSub.

Added it here, it should also work directly with Mosca.

PS:
Did not change the version number in package.json ;-)

### CODE REVIEW

**Comment by mcollina** [comment]
This will require unit tests to be merged in.

**Comment by bobvanluijt** [comment]
Yeah I thought so.

Am a bit in dubio what to do with the Gcloud credentials...

**Comment by mcollina** [comment]
those will need to be encoded using travis
Il giorno gio 25 ago 2016 alle 13:02 Bob van Luijt <notifications@github.com>
ha scritto:

**Comment by bobvanluijt** [comment]
Never did that in a pull request. Can I do that on another Travis?

**Comment by mcollina** [comment]
You can also add a unit test and tell me that if I add the credentials it passes.
I can do that myself, but provide instructions on how to get those.

You might want to have a look at https://github.com/mcollina/mqemitter, that is a standard API for pubsub that is split across multiple repositories. It's easier to add your mqemitter-google-pubsub.

**Comment by bobvanluijt** [comment]
I'm not sure I follow. Is mqemitter integrated in Ascoltatori and Mosca? Thx

**Comment by mcollina** [comment]
A new, experimental version of a MQTT broker based on Mqemitter is available at http://npm.im/aedes

**Comment by bobvanluijt** [comment]
You mean _instead_ of Ascoltatori?

**Comment by bobvanluijt** [comment]
Hi @mcollina, was curious if you had seen my latest comment ;-)

Was curious about this, because if you are going to focus on Aedes mainly, it makes more sense to build it in there.

Thanks in advance

**Comment by mcollina** [comment]
that's the idea, yes :)

**Comment by bobvanluijt** [comment]
Aha, awesome, I will focus on that one instead 👍

**Pull request closed without merging**
