### PR TITLE
Introduce ioredis & msgpack

### PR DESCRIPTION
**Pull request by behrad**
Redis persistence is compatible with ioredis, when requiring ioredis constructor in. 
Options can be set via redisOptions

### CODE REVIEW

**Comment by mcollina** [comment]
I think we can just switch to ioredis, and remove the need for passing in the `'redis'` module. This is a tiny breakage (will bump the major), but I think it's way better. We'll need to update the docs in mosca.

**Comment by behrad** [comment]
If you can do the merge & release today, I'm updating the PR.

**Comment by behrad** [comment]
This should not affect current deployments despite the configuration change. 
All redis options are now passed flat to the ascoltatori.

**Comment by behrad** [comment]
Would you please check this @mcollina ? Fails seem not be related to this commit

**Comment by mcollina** [comment]
I have not much time to look into it. It seems some incompatibility somewhere in node v0.12 :(.
We can't drop that, unfortunately.

**Comment by behrad** [comment]
seems a `microtime` build error when building `leveldown`!!

**Pull request merged**
