### PR TITLE
use standard NodeJS callback style; closes #51

### LINKED ISSUE #51: Implement deferred open

### PR DESCRIPTION
**Pull request by boneskull**
I assume tests are broken, but see #121.

### CODE REVIEW

**Comment by mcollina** [comment]
Tests are not broken, so they need to be fixed. Also the README needs an
update.
Il giorno mar 30 giu 2015 alle 00:55 Christopher Hiller <
notifications@github.com> ha scritto:

**Comment by boneskull** [comment]
What I meant to say was that I have no idea if this breaks tests, but it seems like it should. But because of #121, I don't know how to run the tests to fix them.

**Comment by mcollina** [comment]
The problem with this is that, in order to support the Node callback style, you should change the factory, so that the instance is at the second place, and not at the first. https://github.com/mcollina/ascoltatori/blob/master/lib/ascoltatori.js#L84-L88

**Comment by boneskull** [comment]
@mcollina I made those changes in the PR [already](https://github.com/mcollina/ascoltatori/pull/122/files#diff-1eb0a91b9e513b82c464404132409995L86)

**Comment by boneskull** [comment]
trying to test now

**Comment by boneskull** [comment]
all tests pass on my end.

**Comment by mcollina** [comment]
Great!

Ok, would you mind updating the README, too?

This needs to be released as 1.0.0, as it breaks the API.

**Comment by boneskull** [comment]
@mcollina done

**Comment by mcollina** [comment]
Great! Would you like to help maintaining this module? :)

**Comment by boneskull** [comment]
@mcollina Thanks for the offer, but I can't really commit to anything.  Too many projects, too little time...

**Comment by boneskull** [comment]
(@mcollina Got my hands full with [Mocha](/mochajs/mocha) and my own projects)

**Comment by mcollina** [comment]
Oh yes. I am exactly in the same situation!
Il giorno ven 10 lug 2015 alle 21:13 Christopher Hiller <
notifications@github.com> ha scritto:

**Pull request merged**
