### PR TITLE
Add support for amqplib

### PR DESCRIPTION
**Pull request by phucpnt**
Hello,

I hope this feature would be put into mainstream.

Regards
Phuc

### CODE REVIEW

**Comment by mcollina** [comment]
Can you add this to the README?

**Comment by mcollina** [comment]
all unit tests are failing https://travis-ci.org/mcollina/ascoltatori/jobs/158252830.

**Comment by phucpnt** [comment]
@mcollina I saw it, will do the update and let you know

**Comment by phucpnt** [comment]
@mcollina I has updated the PR. The readme also updated. I check the test and it passed

any concern to merge the pr?

**Comment by mcollina** [comment]
@phucpnt there are still lots of console.log in the PR https://travis-ci.org/mcollina/ascoltatori/jobs/158910023#L1314.

**Comment by phucpnt** [comment]
@mcollina my bad, I has remove the `console.log`

**Comment by mcollina** [comment]
Released as v3.1.0.

**Pull request merged**
