### PR TITLE
Kafka use high level consumer

### PR DESCRIPTION
**Pull request by svarkey**
Added an option to use Kafka high level consumer. By default system uses the simple consumer and this can be overridden

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add some tests for this? Probably we need to run the full abstract suite with this option enabled, see https://github.com/mcollina/ascoltatori/blob/master/test/kafka_ascoltatore_spec.js.

**Comment by svarkey** [comment]
@mcollina Sure i can add tests But how can i run kafka test suite?  Is it some kinda run time variables. Can you please help me on this  

Also i notice the existing builds are failing

**Comment by mcollina** [comment]
You will need to double https://github.com/mcollina/ascoltatori/blob/master/test/kafka_ascoltatore_spec.js with the new setting.

Mongo is flaky :(, don't worry.

**Comment by svarkey** [comment]
Added tests to cover this new setting. Please review 

Thanks
Sanchu

**Pull request merged**
