### PR TITLE
Fix topic.replace is not a function

### PR DESCRIPTION
**Pull request by junwatu**

### CODE REVIEW

**Comment by JoalePampala** [comment]
:+1:

**Comment by dario1985** [comment]
Any problem with this PR? Can I help? 
It prevents to upgrade nodejs-redis to >=2.0 (current stable 2.3!)...

**Comment by mcollina** [comment]
Tests are failing on CI. I have little time to figure it out :).

Some more problems: this is needed to bump redis to 2.0.0, but Redis is not bumped inside package.json.

If you want to help, can you submit another pull request that bumps redis and passes on Travis?

Thanks @dario1985 !

**Comment by behrad** [comment]
#137 should be merged first @mcollina

**Comment by mcollina** [comment]
Fixed in 2.0.0.

**Pull request closed without merging**
