### PR TITLE
V2 dev

### PR DESCRIPTION
**Pull request by mcollina**
same as #140 but releases as 2.0.0-pre1

cc @psorowka

### CODE REVIEW

**Comment by mcollina** [comment]
@psorowka have you got that Mosca PR ready? Point it to ascoltatori 2.0.0-pre1. We'll go through a couple of releases before getting this out, but it's doable.

**Comment by psorowka** [comment]
I am busy with the kids today but am prepared to file the mosca pr tonight. I think the latest version in cybusio/mosca#node4 should be very close, just missing the new ascoltatori dep

Gesendet mit TypeApp

**Comment by psorowka** [comment]
shall we merge that into master now? I can also make the intermediate mosca version with git dep

**Comment by psorowka** [comment]
update.. sorry didnt realize you had already published 2.0.0-pre1 to npm :) didn't see it here https://www.npmjs.com/package/ascoltatori how could you hide that?

**Comment by mcollina** [comment]
Look into https://docs.npmjs.com/cli/dist-tag. You can `npm publish -t stable` to publish the package under the 'stable' dist-tag instead of latest. Latest is what is displayed on the website and installed by default.

**Comment by psorowka** [comment]
never stop learning..

**Comment by psorowka** [comment]
looks good!

**Comment by dario1985** [comment]
@psorowka, @mcollina thank you so much for merging this!

**Pull request merged**
