### PR TITLE
add Vagrantfile; closes #121

### LINKED ISSUE #121: "npm test" fails
Probably because I don't have a broker running, but there are no instructions on how to set up the test environment. 

From what I can gather from `.travis.yml`, I need:

- MongoDB
- Whatever this does: `(cd node_modules/mosca/node_modules && rm -rf ascoltatori && mkdir ascoltatori && tar -c --exclude node_modules ../../.. | tar -x -C ascoltatori)`
- RabbitMQ
- Redis
- `libzmq3-dev`

If you're going to force pre-commit hook(s), it should at least be trivial to run the tests.  So, either all this stuff is installed via a `prepublish` script--for Linux, Windows, and Darwin--or the pre-commit hook(s) should be removed.

### PR DESCRIPTION
**Pull request by boneskull**
- modified `CONTRIBUTING.md` w/ relevant info

I've created a [Vagrant box](https://atlas.hashicorp.com/boneskull/boxes/ascoltatori) with the prerequisites installed, which is publicly available.

@mcollina If you create an account on [Atlas](http://atlas.hashicorp.com), I will give you write access to the box. Let me know if you have any other questions.

### CODE REVIEW

**Comment by mcollina** [comment]
My atlas account is matteocollina. How do I update that box?

**Comment by boneskull** [comment]
@mcollina Since I *assume* we're unlikely to update it often, I didn't write a build script.  If this is necessary, I can provide one using Ansible.

So, for now, if you need to update the box:

1.  Follow install instructions in `CONTRIBUTING.md` thru `vagrant up`
2.  `vagrant ssh`
3.  Do whatever you need to (`apt-get install foo`, etc.)
4.  exit the machine
5.  From the host, execute `vagrant package`, which will generate a new `.box` in the current dir.
6.  Navigate Atlas' UI to upload & release a new version of the box.

I've given you admin rights to the box.

**Comment by boneskull** [comment]
re: builds, building w/ [Packer](https://packer.io/) is likely going to be way faster than doing it manually (especially since you can setup any number of providers; right now we just have `virtualbox`).  You can configure your "Packer template" with one or more provisioning tools, such as ansible.  then, you can upload this configuration (or provide it on GitHub or something) to Atlas.  There's some sort of GitHub Atlas service which is notified when you push to the build configuration repo.  When you do, a new build is started on Atlas, creating boxes for each provider.  I think then it's trivial to release a new version.

There should/may be some sort of CI, so when a build is finished, your tests are executed, so you know it's safe to release.  

I think we may also be able to have Travis `vagrant up` and simplify `.travis.yml`

**Comment by boneskull** [comment]
if you're curious, I built this on top of the latest `precise` box.

- ssh'd into machine
- add Chris Lea's `redis-server` PPA; `apt-get update && apt-get install nodejs -y` (0.12.x)
- add Nodesource's `nodejs` PPA; `apt-get update && apt-get install redis-server -y`
- after this realized probably didn't need PPAs
- `apt-get install rabbitmq-server`
- `apt-get install mongodb`
- `apt-get install libzmq3-dev`
- `apt-get install git g++ make` (this is required to build various npm modules)

After this, I was able to get `npm test` to pass.

**Comment by mcollina** [comment]
Really thank so much for this!

**Pull request merged**
