### PR TITLE
v3-dev

### PR DESCRIPTION
**Pull request by mcollina**
This pull requests deprecates node v0.10 and adds in node v6, moves from redis to ioredis #146, adds kafka support #144.

@behard @fullergalway please review and test.

@davedoesdev I am currently blocked on https://github.com/davedoesdev/qlobber-fsq/issues/4.

### CODE REVIEW

**Comment by davedoesdev** [comment]
Yep, working on it (finishing up tests on Lunux, testing on Windows). Should be a couple of days.

**Comment by davedoesdev** [comment]
`qlobber-fsq` v2.0.0 is now published:

- changes `fs-ext` to an optional dependency
- adds a `single` option when constructing to disable work queue semantics
- auto-detects when `fs-ext` isn't available, emitting a `single_disabled` event

Also tested on Windows (without work queue semantics - tests modified to account for this case).

**Comment by mcollina** [comment]
@davedoesdev can you please have a look at https://travis-ci.org/mcollina/ascoltatori/jobs/127988619#L1479? Can we get those removed here? Or it's fine?

**Comment by fullergalway** [comment]
I will try to do some testing with a mosca and kafka ascoltatori today.

Regarding "Cannot find module 'fs-ext'" warnings for the fs ascoltatore, might this be fixed by adding [fs-ext](https://www.npmjs.com/package/fs-ext) as a dependency in package.json...?

**Comment by mcollina** [comment]
It's in the optionalDependencies of qlobber-fsq, but it does not get compiled on node v6.

**Comment by davedoesdev** [comment]
@mcollina yes we can get rid of these.  Add this line:

```javascript
opts.single = false;
```

here: https://github.com/mcollina/ascoltatori/blob/master/lib/filesystem_ascoltatore.js#L20

**Comment by davedoesdev** [comment]
Btw, `fs-ext` should install on Node 6 (does on my box).

**Comment by fullergalway** [comment]
Quick update: having some trouble testing kafka ascoltatori with mosca.

Mosca publishes metadata about user subscribes/unsubscribes etc. to $SYS* topics. Dollar sign is not allowed as kafka topic name so it breaks (uncaught error) when trying to create the topic. I'm unsure how best to resolve because a) there's no easy way to map non-allowed characters and allowed-characters, and b) I'm conflicted about the utility of many $SYS topics being created in my kafka(!).

I'm considering something like a Filter Ascoltatore which would be backed by two (or more?) delegate ascoltatores. This would allow me to filter all the $SYS topics to a different backend (eg., a file), while retaining the actual data topics in kafka.

Suggestions welcome.

**Comment by mcollina** [comment]
@fullergalway so the `$SYS` topics are needed 1) for stats and 2) by the persistence layer to synchronize the various instances of Mosca. Disabling stats is quite easy, while the second can cause issues.

I think a simple solution is to escape the $.

**Comment by mcollina** [comment]
@psorowka would you like to take this for a spin before I release it as v3?

**Pull request merged**
