### PR TITLE
Update redis_ascoltatore.js

### PR DESCRIPTION
**Pull request by sumitkumar**
Topic should not be tampered with. 
We encountered a problem with topic mismatch in mosca since we had with trailing slash in topic.
Please merge or else we will have to fork and do our own maintenance for a small character fix.

### CODE REVIEW

**Comment by mcollina** [comment]
The tests are failing, as that little thing is kind of needed to make this work.
Can you please articulate better what is your problem, and what you want to achieve?
Trailing '/' are kind of weird in MQTT anyway, and it is much better to avoid them anyway.

BTW, saying 'we are going to fork' is not a good attitude.

**Comment by sumitkumar** [comment]
The issue is that the behavior is not consistent with mongo and redis. In the mongo_ascoltatore trailing '/' is allowed but not in redis_ascoltatore. In mongo it wasn't working with multiple mosca processes. With redis it works but the trailing '/' is making it tamper with the topic.

I understand it is good practice to avoid trailing slash but this is the first mqtt broker(when used with redis) which is forcing this practice. Nowhere topic has been altered by the broker.

It is not a matter of attitude, but it was our observation that it was breaking the expected behavior.

**Comment by mcollina** [comment]
It _is_ a matter of attitude. Saying 'merge or fork' is a _really bad behavior in oss_, which I cannot tolerate. As this is free as in beer, and this is free support, you are free of maintaining your fork whenever you like.

I am keen on getting this fixed, it is just that the proposed fix is not right as it breaks the tests. It might work for your application, but not in general and for everybody. The basic 'hello' test fails, so I doubt it will work for you either.

**Comment by sumitkumar** [comment]
Well, apologies if I came off as someone brash and not with a good attitude. I know it is not an excuse but english is not my first language and though I have used mostly OSS only in my life I am still not too familiar with how the OSS community works and what is cool and what is not. 

The plea to merge was a request and nothing else. Which is why I mentioned that it is not about attitude. I have high regards for your work and it has really helped us in building a quick prototype for our use case application and soon it will be going to production. So, thank you for that.

**Comment by mcollina** [comment]
Good! :)

There is some level of weirdness in how the Redis stuff works, and it's all
related to /, # and +. The ley problem is that Redis does not support any
of those, but * which means 'any character'. This is the reason we 'change'
the topic.

All that logic, including removing / at the end, is to add those features
on top of Redis. I am cool in improving the conformity of Redis, but I
currently have little time to figure out a new algorithm. Woul you like to
help?
Il giorno gio 28 mag 2015 alle 03:58 Sumit Kumar <notifications@github.com>
ha scritto:

**Pull request closed without merging**
